### ISSUE TITLE
Source code of bayesian sigmoid curve fitting

### ISSUE THREAD

**Issue by hsiaoyi0504** [CSB5/CaDRReS#1]
In the manuscript, it mentions that **bayesian sigmoid curve fitting** approach was applied to raw intensity data at different drug dosages to re-compute IC50. Will these part of source code be released ?

**Comment by nokcs** [comment]
Thank you for your interest. Yes, we can release the source code for Bayesian sigmoid curve-fitting in few days.

**Comment by nokcs** [comment]
Hi @hsiaoyi0504 , I have uploaded a script for Bayesian sigmoid curve fitting. Please check here https://github.com/CSB5/CaDRReS/tree/master/scripts/bayesian_sigmoid_curve_fitting.
