### ISSUE TITLE
Why calculate a new IC50?

### ISSUE THREAD

**Issue by EularTang** [CSB5/CaDRReS#2]
Hi,
The GDSC Provided the IC50 of the drug. Why calculate a new IC50? What are the advantages of the newly IC50?
Thanks for your attention!
Bests

**Comment by nokcs** [comment]
Hi EularTang,

The IC50 values provided by CCLE and GDSC were estimated differently. Also, CCLE set the maximum IC50 to the maximum concentration used in their experiments. Therefore, we reestimated the IC50 values by using the same method. We found that the newly estimated IC50s were more comparable across datasets (Supplementary Fig. S1; [CaDRReS's paper](https://academic-oup-com.ejproxy.a-star.edu.sg/bioinformatics/article/34/22/3907/5026663)).

Hope this help.

Best Regards,
Nok

**Comment by EularTang** [comment]
Hi Nok,
I has used your significant tool , thank you for your contribution!

However,I faced some confusions about the tool:

Firstly,According to your tutorial,the input of the CaDRReS_train_and_test.py ,''drug_response_ic50_test.csv'', is an empty matrix where rows are cell lines and columns are drugs. Why is my output, CaDRReS_pred_end, also empty「fig.1」?

Secondly,Is the model prediction of the drug response measured using the IG50? Why is the value in the CaDRReS_pred_end_train matrix in the output file around 4, and it is very different from the IG50 value of the input file?

Thirdly, cell_line_features.csv contains a feature matrix. I noticed that the ccle_cellline_pcor_ess_genes you used in the example is a similarity matrix between cell lines「fig3」. So when I use my own expression profile for prediction, should this feature be a similarity matrix?How is this similarity matrix calculated?

My commond:
`python CaDRReS_train_and_test.py ../input/train.csv ../input/test.csv ../input/ccle_cellline_pcor_ess_genes.csv ../misc/ccle_drugMedianGE0.txt ../../../ 10 1000 0.01 0`

Thank you very much!
Best regards,
Tang

Fig.1
![image](https://user-images.githubusercontent.com/37855187/60016048-a56bd580-96b7-11e9-82c4-cf20580407ba.png)

Fig.2
![image](https://user-images.githubusercontent.com/37855187/60015989-73f30a00-96b7-11e9-98b9-6e08e47a51d9.png)
Fig.3
![image](https://user-images.githubusercontent.com/37855187/60016017-8c632480-96b7-11e9-815e-be7937bf0132.png)

**Comment by nokcs** [comment]
Hi Tang,

For the first question, are you predicting the drug response for your own samples? The input feature file (../input/ccle_cellline_pcor_ess_genes.csv) should also contain features for the testing samples.

The model learns based on IC50 values to predict IC50 values. Thank you for pointing out this. It seems like I accidentally pushed some old output files. I have uploaded new prediction files for both CCLE and GDSC.

For the last question, the kernel features were calculated based on log2(gene expression) normalized per gene, i.e. for GeneA, the values will be log2(GeneA) - median(log2(GeneA in all samples))). The value in the table is a pearson correlation between the samples based on expressions of essential genes (misc/essential_genes.txt).

Best Regards,
Nok

**Comment by EularTang** [comment]
Hi Nok,

Thank you for your reply.

I have not applied my own data yet. Data ''ccle_all_abs_ic50_bayesian_sigmoid'' was split into two parts by me. After the first twenty lines as test, the value  was removed and the rest was used as train.
It seems that there is no need to change the input feature file.

My two output files, CaDRReS_pred_end and CaDRReS_pred_end_train, still encountered the previous problems.I put the output and input into [onedrive](https://tongjieducn-my.sharepoint.com/:f:/g/personal/chentang_tongji_edu_cn/EhiPTyeXb7RJiVmBeDCUc3wB5Pt4khn6Ga35NcsxoAHAPg?e=TiwmVO), where you can click to check

My commond:
`python CaDRReS_train_and_test.py ../input/train.csv ../input/test.csv ../input/ccle_cellline_pcor_ess_genes.csv ../misc/ccle_drugMedianGE0.txt ../../../ 10 1000 0.01 0`

Best regards,
Tang

**Comment by nokcs** [comment]
Hi Tang,

Could you try max_iterations=50000 instead of 1000 for CCLE? I think the model is not converged yet at 1000 iterations.

**Comment by EularTang** [comment]
Hi Nok,

After max_iterations=50000, the result in ''CaDRReS_pred_end_train '' has been significantly improved, but the result of ''CaDRReS_pred_end'' is still empty「Fig.2」. Is there a problem with my input file ''test'' 「Fig.1」?

Fig.1
![image](https://user-images.githubusercontent.com/37855187/60069972-8d439700-9747-11e9-9a1d-5c2691fd248d.png)

Fig.2 
![image](https://user-images.githubusercontent.com/37855187/60069987-99c7ef80-9747-11e9-8d55-130249db444b.png)

**Comment by nokcs** [comment]
May I confirm with you again that, in the onedrive folder that you shared with me for the previous result,  CaDRReS_pred_end is not empty? 

![Capture](https://user-images.githubusercontent.com/11409990/60070387-01326f00-9749-11e9-867f-43482e411f36.PNG)

**Comment by EularTang** [comment]
Hi Nok,

Sorry, I chose the wrong file. This is the result of not clearing the value of ''test.csv ''of the input. At this time, the result of ''CaDRReS_pred_end'' is not empty;

But if ''test.csv is an empty matrix, then the result is also empty.

I have updated the output in the hyperlink.

Tang

**Comment by nokcs** [comment]
Hi Tang,

I see. It is probably because in the preprocessing step the script excludes those rows with no drug response information. The reason behind is we keep track of the model performance for every 1000 iterations, i.e. the script calculates the prediction accuracy for both train and test data. You may initiate the test.csv with all zero and ignore the testing performace reported in the pickle file.

Could you also share with me the output of the script? While you are training the model, the script should print out the status.

Best Regards,
Nok

**Comment by EularTang** [comment]
Hi Nok,

I have put the  log file into the updated onedrive; since I have an exam after an hour, in order to save time, max_iterations is set to 5000; you can see the results of higher max_iterations next morning. 
Thank you again for your attention.

Best Regards,
Tang

**Comment by nokcs** [comment]
Hi Tang,

Thank you for sharing the log file. The script removed those empty lines in test.csv as I described previously (Line 5 in the log file). You may initiate the test.csv with all zero and ignore the testing performance reported in the pickle file. Sorry for the inconvenience caused.

Best Regards,
Nok
