### ISSUE TITLE
GDSC dose response scores .zip file

### ISSUE THREAD

**Issue by MashaAseeva** [CSB5/CaDRReS#3]
I am trying to download the GDSC_dose_response_scores.zip file.
When I try to open this file, I get the error:

`  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of GDSC_dose_response_scores.zip or
        GDSC_dose_response_scores.zip.zip, and cannot find GDSC_dose_response_scores.zip.ZIP, period.`

It appears that the file is broken. Is there a special way I should be reading this/opening this?

**Comment by nokcs** [comment]
I have updated the download link in [this page](https://github.com/CSB5/CaDRReS/tree/master/scripts/bayesian_sigmoid_curve_fitting). You can download the unzip file for GDSC dataset.

**Comment by MashaAseeva** [comment]
Thank you!
