### ISSUE TITLE
cannot get the result in the literature 

### ISSUE THREAD

**Issue by fishguysword** [CSB5/CaDRReS#4]
I use the command like 
python CaDRReS_train_and_test.py   ../input/cv/ccle_cv_5f_train_2.csv  ../input/cv/ccle_cv_5f_test_2.csv   ../input/ccle_cellline_pcor_ess_genes.csv   ../misc/ccle_drugMedianGE0.txt   ../output 10 50000  0.01  0 

I foud that the test_dataset ndcg reduce from 1000 to 50000 although the train_dataset ndcg increase.
I just got the test ndcg result  just 0.46

**Comment by fishguysword** [comment]
solved,  test=test*-1

**Comment by FatimaIqbal-BI** [comment]
hello, would you please help me run this code, how to do that please tell me the steps
